#!/bin/sh
# AKA-00 startup — called by aka-server or directly
# cd to project dir first, or set AKA_HOME

APP_DIR="${AKA_HOME:-/root/AKA-00}"

chmod +x "$APP_DIR/uart_init.sh" 2>/dev/null || true
"$APP_DIR/uart_init.sh"

# SSL cert auto-generated by run.py, skipping https_init.sh

exec python3 "$APP_DIR/run.py"
