ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
ap_scan=1
update_config=1 #这个配置使wpa_cli命令配置的热点保存到conf文件里面（wpa_cli save_config）
country=CN
#STA配置项
network={
    ssid="Tsinghua-Dongsheng"
    key_mgmt=NONE
}
